services:
  gateway:
    build: 
      context: ./services/gateway
    container_name: gateway_service
    ports:
      - "8000:8000"
  
  auth:
    build:
      context: ./services/auth
    container_name: auth_service
    ports:
      - "8001:8000"
  